{
    "error": {
        "task": "task_palindrome",
        "test_name": "py.test_task_palindrome.PalindromeTestCase.test_10",
        "test_description": "Tests the main functional",
        "error_type": "fail",
        "error_message": "True != False",
        "traceback": "Traceback (most recent call last):\n  File \"/python_packages/hamster_core/unit_test/decorators.py\", line 64, in wrapper\n    func(self, dataset, result)\n  File \"/data/tests/py/test_task_palindrome.py\", line 42, in test_10\n    self.assertEqual(self.answer, result)\nAssertionError: True != False\n",
        "context": {
            "expected_result": false,
            "dataset_number": 2,
            "dataset": {
                "dataset": "\u042f \u0431\u044b \u0438\u0437\u043c\u0435\u043d\u0438\u043b \u043c\u0438\u0440, \u043d\u043e \u0431\u043e\u0433 \u043d\u0435 \u0434\u0430\u0435\u0442 \u0438\u0441\u0445\u043e\u0434\u043d\u0438\u043a\u0438"
            },
            "result": true
        }
    }
}